import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Instagram App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <div className="flex h-full w-full">{children}</div>;
}
