import type { Metadata } from "next";
import SideBar from "../(routes)/_components/side-bar";
import MobileBar from "./_components/mobile-bar";
import MediumBar from "./_components/medium-bar";

export const metadata: Metadata = {
  title: "Instagram App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex h-full w-full">
      <div className="hidden lg:block sticky h-full top-0">
        <SideBar />
      </div>
      <div className="hidden sm:block lg:hidden">
        <MediumBar />
      </div>
      <div className="fixed w-full bottom-0 right-0 block sm:hidden z-[10000]">
        <MobileBar />
      </div>

      <div className="h-full w-full ">{children}</div>
    </div>
  );
}
