import type { Metadata } from "next";
import SideBar from "./_components/_nav/side-bar";
import MobileBar from "./_components/_nav/mobile-bar";
import MediumBar from "./_components/_nav/medium-bar";
import { useEffect } from "react";

export const metadata: Metadata = {
  title: "Instagram App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex">
      <div className="hidden lg:block sticky top-0 h-screen">
        <SideBar />
      </div>
      <div className="hidden sm:block lg:hidden sticky top-0 h-screen">
        <MediumBar />
      </div>
      <div className="fixed w-full bottom-0 right-0 block sm:hidden z-[10000]">
        <MobileBar />
      </div>

      <div className="w-full py-4">{children}</div>
    </div>
  );
}
